name: Deploy 'sdks.near' App Components to Mainnet

on:
  push:
    branches: [main]
    paths:
      - widget/**

jobs:
  deploy-mainnet:
    uses: nearbuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      deploy-env: "mainnet"
      app-name: "sdks.near"
      deploy-account-address: sdks.near
      signer-account-address: sdks.near
      signer-public-key: ${{ vars.SIGNER_PUBLIC_KEY }}
    secrets: 
      SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}